### ISSUE TITLE
Cannot start nuxt:  Failed to get devtools context.

### ISSUE THREAD

**Issue by larrasu** [nuxt/fonts#149]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.1`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@8.6.11`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `hub`, `nitro`
- Runtime Modules:  `@nuxthub/core@0.5.16`, `@nuxt/eslint@0.3.10`, `nuxt-icon@0.6.10`, `@nuxtjs/tailwindcss@6.12.0`, `@nuxt/fonts@0.7.0`
- Build Modules:    `-`

### Version

v0.7.0

### Reproduction

https://stackblitz.com/~/github.com/larrasu/frontend-mentor

```sh
cd solutions/invoice-app
pnpm dev
```

### Description

I've been experiencing this error in various projects. I'm not sure why I can't reproduce the error on Stackblitz. It's the same repo and branch. The error is still showing up on my end as of now. The only way to get rid of this error is by removing `@nuxt/fonts` from the `nuxt.config.ts`. So I figured there is a conflict between`@nuxt/fonts` and `@nuxt/devtools`?

### Logs

```sh
 ERROR  Cannot start nuxt:  Failed to get devtools context.                         12:09:04 AM

  at extendServerRpc (node_modules/.pnpm/@nuxt+devtools-kit@1.2.0_nuxt@3.11.2_vite@5.2.11/node_modules/@nuxt/devtools-kit/dist/index.mjs:96:11)
  at node_modules/.pnpm/@nuxt+fonts@0.7.0_nuxt@3.11.2_vite@5.2.11/node_modules/@nuxt/fonts/dist/module.mjs:1137:11
  at node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:66
  at Object.run (node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:41:43)
  at node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs:48:56
  at async enableModule (/Users/larrasu/.nvm/versions/node/v16.15.1/lib/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:8466:3)
  at async normalizedModule (/Users/larrasu/.nvm/versions/node/v16.15.1/lib/node_modules/@nuxt/devtools/node_modules/@nuxt/kit/dist/index.mjs:169:17)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.59.4_drizzle-orm@0.30.10_eslint@9.2.0_fl_br3acc34oknouixgtiqiyrhd6y/node_modules/nuxt/dist/index.mjs:4233:7)
  at async NuxtDevServer._load (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/dev2.mjs:6879:5)
```

**Comment by danielroe** [comment]
@larrasu my apologies for not checking this out earlier.

I see the reproduction is not accessible, so let's track in https://github.com/nuxt/fonts/issues/106 - let me know if you can provide a reproduction and I'll reopen. 🙏
